name: Maven Package - Multi stage docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker build
      run: |
        docker build . -t gitauwairimu/javamvn:${GITHUB_RUN_ID}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push gitauwairimu/javamvn:${GITHUB_RUN_ID}

    - name: Checkout K8s manifest repo
      uses: actions/checkout@v2
      with:
        repository: Gitauwairimu/GitOps--ghjavamvn
        ref: 'main'
        # export GITHUB_TOKEN=$(secrets.k8s_REPO_UPDATE)
        # token: ${{ secrets.k8s_REPO_UPDATE }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./base
      env:
        GITHUB_TOKEN: ${{ secrets.k8s_REPO_UPDATE }}

    - name: Set ${GITHUB_RUN_ID}
      run: echo "${GITHUB_RUN_ID}" > .github/workflows/run_id
    - name: Wait for ${GITHUB_RUN_ID}
      run: wait
    - name: Update k8s manifest with new image
      run: |
        cd base/base
        sed -i "s|image: .*|image: gitauwairimu/javamvn:${GITHUB_RUN_ID}|g" deployment.yaml

    - name: setup git config
      run: |
        cd base
        git config user.name "charles"
        git config user.email "gitauwairimu@gmail.com"
        git add base/deployment.yaml
        git commit -m 'updated k8s manifest image version'
       
        # git remote set-url origin https://Gitauwairimu:${{ secrets.GITHUB_TOKEN }}@github.com/Gitauwairimu/GitOps--ghjavamvn.git
        # git remote set-url origin https://github.com/Gitauwairimu/GitOps--ghjavamvn.git
        # git push https://${{ secrets.k8s_REPO_UPDATE }}@github.com/Gitauwairimu/GitOps--ghjavamvn.git
        # git push https://${{secrets.ACTIONS_RUNNER_TOKEN}}@github.com//Gitauwairimu/GitOps--ghjavamvn.git -f
        # git push origin main

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_RUNNER_TOKEN }}
        repository: Gitauwairimu/GitOps--ghjavamvn
        branch: main
        force_with_lease: true
      # env:
      #   GITHUB_TOKEN: ${{ secrets.k8s_REPO_UPDATE }}

    - uses: fastify/github-action-merge-dependabot@v2.1.1
      with:
        github-token: ${{ secrets.ACTIONS_RUNNER_TOKEN }}

    # - name: Push Repo changes
    #   uses: EndBug/add-and-commit@v7
    #   with:
    #     cwd: ./base
    #     message: 'update image version'
    #     branch: main


