name: Maven Package - Multi stage docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker build
      run: |
        docker build . -t gitauwairimu/javamvn:${GITHUB_RUN_ID}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push gitauwairimu/javamvn:${GITHUB_RUN_ID}

    - name: Checkout K8s manifest repo
      uses: actions/checkout@v2
      with:
        repository: Gitauwairimu/GitOps--ghjavamvn
        ref: 'main'
        # export GITHUB_TOKEN=$(secrets.k8s_REPO_UPDATE)
        # token: ${{ secrets.k8s_REPO_UPDATE }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ./base
      env:
        GITHUB_TOKEN: ${{ secrets.k8s_REPO_UPDATE }}

    - name: Update k8s manifest yaml
      run: |
        cd base/base
        sed -i 's/image*/"image: gitauwairimu/javamvn:${GITHUB_RUN_ID}"/g' deployment.yaml
        cat deployment.yaml
    - name: setup git config
      run: |
        git config user.name "Charles GitHub Actions Bot"
        git config user.email "wcharlesgitau@gmail.com"
        git add /base/deployment.yaml
        git commit -m 'updated k8s manifest'
        git push origin main

    - name: Push Repo changes
      uses: EndBug/add-and-commit@v7
      with:
        cwd: ./base
        message: 'update image version'
        branch: main




                  # sed -i 's/^image: gitauwairimu/javamvn.*/image: gitauwairimu/javamvn:${GITHUB_RUN_ID}/' ./base/deployment.yaml