name: Maven Package - Multi stage docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  deployments: write
  contents: write
  id-token: write
  actions: write
  checks: write
  discussions: write
  issues: write
  pages: read
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: zuma
  GCE_INSTANCE_ZONE: us-east1-d

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Build with Maven
      run: tree

    - name: List Files
      run: ls

    - name: Docker build
      run: |
        docker build . -t gitauwairimu/javamvn:${GITHUB_RUN_ID}
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push gitauwairimu/javamvn:${GITHUB_RUN_ID}
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker


    - name: Deploy on GCP
      run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "gitauwairimu/javamvn:${GITHUB_RUN_ID}"
      # --container-image "gcr.io/$PROJECT_ID/$GCE_INSTANCE-image:$GITHUB_SHA"





# gcloud compute instances create-with-container zuma --project=pork-merchant --zone=us-east1-d --machine-type=e2-small --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=sc-zuma@pork-merchant.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/cloud-platform --tags=http-server,https-server --image=projects/cos-cloud/global/images/cos-stable-109-17800-0-47 --boot-disk-size=10GB --boot-disk-type=pd-balanced --boot-disk-device-name=zuma --container-image=push\ gitauwairimu/javamvn:6456804406 --container-restart-policy=always --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud,container-vm=cos-stable-109-17800-0-47